### ISSUE TITLE
AdCampaign entities model

### ISSUE THREAD

**Issue by david-amaya-acruz** [miw-upm/apaw-practice#101]
![image](https://user-images.githubusercontent.com/71399832/95191275-d1d63300-07d0-11eb-911c-a21e484152f0.png)

**Comment by miw-upm** [comment]
Hola David, acuerdate que siempre que un issue# incorpora a develop, debe ser sin avance rápido: con develop activo:
**git merge --no-ff -m"merge #??? into develop" issue#???**

**Comment by david-amaya-acruz** [comment]
Cambio de nombres:
Customer por CustomerTarget
Tag por Likes
![image](https://user-images.githubusercontent.com/71399832/95433253-f99fd500-094f-11eb-97ce-c7161a961433.png)

**Comment by david-amaya-acruz** [comment]
Cambio de nombres de entidades para no repetir en la aplicación:
- Customer por CustomerTarget
- Tag porLikes
![image](https://user-images.githubusercontent.com/71399832/95434202-459f4980-0951-11eb-864b-348a0d7b8578.png)
