### ISSUE TITLE
Department model

### ISSUE THREAD

**Issue by HLockward** [miw-upm/apaw-practice#101]
<img width="540" alt="Department model" src="https://user-images.githubusercontent.com/8463126/136847176-bae45b0a-67a4-470d-9753-69aa865056e2.png">

**Comment by miw-upm** [comment]
Antes de incorporar un issue a develop que ha evolucionado, se debe incorporar previamente al issue. 0dbc850c Harold Lockward <hlockward12@gmail.com> on 11/10/2021 at 19:50

**Comment by miw-upm** [comment]
Ya se te avisado antes de como es el flujo de trabajo.
Antes de incorporar un issue a develop que ha evolucionado, se debe incorporar previamente al issue. 9d45c6d7 Harold Lockward <hlockward12@gmail.com> on 11/10/2021 at 21:40

**Comment by HLockward** [comment]
Disculpa, me vine a dar cuenta después de haber incorporado los cambios, no
me había fijado en el warning, pero no volverá a pasar
