### ISSUE TITLE
Persistence design

### ISSUE THREAD

**Issue by netoap** [miw-upm/apaw-practice#108]
1. Crear el modelo de entidades.
2. Crear los DAOs (Repositorios).
3. Crear una clase para poblar las BD: <Story>SeederService e integrarlo con DatabaseSeederService.

**Comment by miw-upm** [comment]
Antes de incorporar un issue a develop que ha evolucionado, se debe incorporar develop al issue: 5b947a76 netoap <alexanderneto5@gmail.com> on 12/10/2021 at 23:55
