### ISSUE TITLE
SEARCH 1: findMachinesByEmployeeDegree

### ISSUE THREAD

**Issue by acalvom** [miw-upm/apaw-practice#129]
Todas las "Machine" que  tienen algún empleado, cuyo title es "???" pasado por parámetro.

**Comment by acalvom** [comment]
Invested time in the issue has been 11 hours (2h + 9h)

**Comment by miw-upm** [comment]
Una estimación solo puede tener una etiqueta de tipo point

**Comment by acalvom** [comment]
> Una estimación solo puede tener una etiqueta de tipo point

De acuerdo, ¿y si estimo un tiempo que no está en los "points"?, ¿Lo creo?

**Comment by acalvom** [comment]
> > Una estimación solo puede tener una etiqueta de tipo point
> 
> De acuerdo, ¿y si estimo un tiempo que no está en los "points"?, ¿Lo creo?

Para los siguientes issues lo tengo en cuenta, pero los que ya están cerrados los dejo como están, ¿no?
