### ISSUE TITLE
Class Model

### ISSUE THREAD

**Issue by sosossss** [miw-upm/apaw-practice#13]

**Comment by miw-upm** [comment]
No se puede trabajar con APAW sin comprender el flujo de trabajo ramificado visto en DEVOPS.  Se recomienda cursar primero la asignatura de IWVG. Los commits generados van a ser eliminados.

**Comment by miw-upm** [comment]
Se debe utilizar adecuadamente el flujo de trabajo visto en devops. No están permitidas las fusiones con ramas remotas: Merge branch 'develop' of https://github.com/miw-upm/apaw-practice into issue#13

**Comment by miw-upm** [comment]
Antes de incorpora a develop, cuando este a evolucionado, se debe incorporar develop a nuestro issue:  295d0ca0 sosossss <wenxiang.wang@alumnos.upm.es> on 03/10/2021 at 21:20

**Comment by miw-upm** [comment]
Hola, si te fijas en el commit anterior, tiene un X ROJA, ello indica que has roto develop y no has hecho nada para arreglarlo, ello perjudica al resto de los alumnos, ya que nadie puede trabajar. Te recomiendo que aprendas como es el flujo de trabajo ramificado antes de incorporar código. Ya tienes demasiados avisos en un solo issue. Un saludo

**Comment by miw-upm** [comment]
Tu código ha sido eliminado y se ha vuelto a un commit estable
