### ISSUE TITLE
Movie entities model

### ISSUE THREAD

**Issue by HectorElGrande** [miw-upm/apaw-practice#13]

**Comment by miw-upm** [comment]
Hola, recuerda que debes asociar a los detalles del issue el diagrama de entidades y espera que le de el visto bueno

**Comment by HectorElGrande** [comment]
![Captura](https://user-images.githubusercontent.com/47184383/94918316-97a82100-04b2-11eb-8243-a540083bbf26.PNG)

**Comment by miw-upm** [comment]
Todo correcto, pero los tipos de los atributos debieran ser de Tipo clase: Boolean. Integer...

**Comment by miw-upm** [comment]
Cuando lo cambies,  ya puedes cerrar el issue y continuar

**Comment by HectorElGrande** [comment]
![Definitiva](https://user-images.githubusercontent.com/47184383/94919131-3aad6a80-04b4-11eb-8d19-22bbfd93a79b.png)

**Comment by HectorElGrande** [comment]
Gracias por la corrección Jesus

**Comment by miw-upm** [comment]
Hola, pero debes cambiarlo también en el código y subirlo... al final de todo ya puedes cerrar el issue
