### ISSUE TITLE
School entities model

### ISSUE THREAD

**Issue by PabloGuijarroMarco** [miw-upm/apaw-practice#14]

**Comment by PabloGuijarroMarco** [comment]
![ClassDiagram](https://user-images.githubusercontent.com/32164392/94918118-31bb9980-04b2-11eb-828c-346aff4fac8b.png)

**Comment by miw-upm** [comment]
Todo correcto, pero los tipos de los atributos debieran ser de Tipo clase: Boolean. Integer...
Cuando lo cambies, ya puedes cerrar el issue y continuar

**Comment by PabloGuijarroMarco** [comment]
![ClassDiagram](https://user-images.githubusercontent.com/32164392/94919874-7ac11d00-04b5-11eb-8bb8-cea8125edfa3.png)

**Comment by miw-upm** [comment]
Hola, pero debes cambiarlo en el código y subirlo
