### ISSUE TITLE
Design Persistance videogame package

### ISSUE THREAD

**Issue by MarioIrving** [miw-upm/apaw-practice#147]
- Create the entity model.
- Create the DAOs (Repositories).
- Create a class to populate the DB: <Story> SeederService and integrate it with DatabaseSeederService

**Comment by miw-upm** [comment]
No se debe fusionar con ramas remotas: Merge remote-tracking branch 'origin/develop' into develop fef31dc0 mario irving <marioirving.morales@gmail.com> on 18/10/2021 at 23:24

**Comment by MarioIrving** [comment]
ai perdón fue un error porque al mismo tiempo que subía subió otro, me gano por un par de minutos.
