### ISSUE TITLE
Music Manager Model

### ISSUE THREAD

**Issue by mangelsanchezUPM** [miw-upm/apaw-practice#15]
Music manager UML model

![](https://raw.githubusercontent.com/miw-upm/apaw-practice/develop/docs/music-manager.models.png)

**Comment by miw-upm** [comment]
Cuando develop ha evolucionado respecto a nuestro punto de partida, antes de incorporar los cambios a develop, debe incorporarse los cambios de develop a nuestra rama issue: bdbe845f Miguel Angel <miguelangelsanchezordaz@alumnos.upm.es> on 29/09/2021 at 21:11
