### ISSUE TITLE
Kitchen entities model

### ISSUE THREAD

**Issue by MRxRafi** [miw-upm/apaw-practice#15]

**Comment by miw-upm** [comment]
Hola, si se pone issue#15, Github no reconoce el issue, debes poner issue  #15 o solo #15

**Comment by MRxRafi** [comment]
> 
> 
> Hola, si se pone issue#15, Github no reconoce el issue, debes poner issue #15 o solo #15

Tienes razón, no aparece en el historial del issue. ¿Se puede solucionar o lo paso por alto?
El próximo lo haré con el formato correcto.
Gracias

**Comment by MRxRafi** [comment]
![KitchenEntities](https://user-images.githubusercontent.com/38105703/95022578-8741a300-0678-11eb-8034-8cf49bf544e2.png)
