### ISSUE TITLE
Sport entities model

### ISSUE THREAD

**Issue by alejandrorsanchez** [miw-upm/apaw-practice#16]
![UML](https://user-images.githubusercontent.com/71324879/94915750-b48e2580-04ad-11eb-8db4-4cfb3c1c3d06.png)

**Comment by miw-upm** [comment]
Hola, 
NO debes hacer avance rápido entre issue# y develop, debes poner: git merge --no-ff -m"merge #? into develop" issue#?
En todos los mensajes debes poner la referencia del issue: bla bla bla y acabas el mensaje con #?

**Comment by miw-upm** [comment]
Los tipos de la clase debierán ser de tipo Class: Integer, Boolean...
