### ISSUE TITLE
Videoclub entities model

### ISSUE THREAD

**Issue by mikelsanabria11** [miw-upm/apaw-practice#173]

**Comment by mikelsanabria11** [comment]
Quería haber puesto de estimación 3h, pero me equivoqué con la etiqueta de "Consumido". Al final he tardado 4h y 45mins

**Comment by miw-upm** [comment]
Hola, antes de incorporar tu issue a develop, debes incorporar develop a tu issue, porque develop había evolucionado r

**Comment by mikelsanabria11** [comment]
Hola Jesús, si lo sé. Te cuento lo que pasó que me di cuenta a posteriori. Cuando acabé el desarrollo en mi rama, antes de hacer nada, hice el correspondiente fetch para ver si develop había avanzado. El caso es que vi que si e intenté realizar el merge de develop con mi issue, pero la consola me decía que “Ya estaba actualizado”. Me resultó raro y lo intenté varias veces, pero entre que era tarde y el cansancio, no me di cuenta de que develop local lo tenia apuntando a donde empezó mi issue. De ahí el mensaje de que ya estaba actualizado

**Comment by miw-upm** [comment]
Hola Mikel, no te preocupes, los warning son para avisar, no quitan punto si no tienes varios, lo importante es tener claro el flujo de trabajo

**Comment by mikelsanabria11** [comment]
![image](https://user-images.githubusercontent.com/71524504/95560664-e0fbf180-0a19-11eb-8e64-374febff374a.png)

**Comment by mikelsanabria11** [comment]
![image](https://user-images.githubusercontent.com/71524504/95632436-eabb3e80-0a85-11eb-9426-3bfe3a54c9a7.png)

**Comment by mikelsanabria11** [comment]
![image](https://user-images.githubusercontent.com/71524504/96331680-825cf600-105f-11eb-85f6-edff5fc9d1b9.png)
