### ISSUE TITLE
Exercises entities model

### ISSUE THREAD

**Issue by bryanjb9** [miw-upm/apaw-practice#176]

**Comment by miw-upm** [comment]
El historial temporal de commits no concuerdan con una secuencia temporal real de desarrollo.
El tiempo consumido debe ponerse una vez que se haya finalizado el issue, no al principio, cuando se empieza a realizar el issue.

**Comment by miw-upm** [comment]
No se está utilizando adecuadamente el flujo de trabajo ramificado

**Comment by bryanjb9** [comment]
![image](https://user-images.githubusercontent.com/30785018/95661915-76d76f80-0b33-11eb-82f1-c32b6084ccc5.png)

Diagrama de clases

**Comment by miw-upm** [comment]
Te recomiendo que aprendas adecuadamente el flujo de trabajo ramificado
