### ISSUE TITLE
Museum Entity Model

### ISSUE THREAD

**Issue by walericalupm** [miw-upm/apaw-practice#209]
Creates an entity model for Museum Business.
A museum has:
- Art Paintings
- Artists (who created Art Paintings)
- Collections (where art paintings are showed)
- Art Restorers (who conserves art paintings) 

With this information, a Entity model will be uploaded in order to be approved by @miw-upm

**Comment by walericalupm** [comment]
A first model draw uploaded to revision from @miw-upm 

![image](https://user-images.githubusercontent.com/37347740/95653409-dd8b6780-0af8-11eb-9e2d-dc391e5f3523.png)

**Comment by walericalupm** [comment]
Third model draw uploaded to revision from @miw-upm 
![Museum Entity Model_3](https://user-images.githubusercontent.com/37347740/96253466-e88c3f00-0fb3-11eb-82be-379fb84276e4.png)

**Comment by miw-upm** [comment]
Para que se registren en el issue los commits, en el mensaje debes incluir "  #209", pero con un blanco delante de la #, por ejemplo: "... issue  #209" o "...  #209 ..."

**Comment by miw-upm** [comment]
No se deben realizar fusiones entre origin/develop con un issue, sólo se permite develop con issue, por eso lo primero es actualizar develop con origin/develop siempre con avance rápido

**Comment by walericalupm** [comment]
A refactoring process will be develop in order to delete redundant Collection entity
Estimate: 2h

**Comment by walericalupm** [comment]
![Museum Entity Model_4_Final](https://user-images.githubusercontent.com/37347740/98481217-1a7e7300-21f9-11eb-928f-636ae0eb84f0.png)
