### ISSUE TITLE
Music entities model

### ISSUE THREAD

**Issue by lihao1214** [miw-upm/apaw-practice#23]

**Comment by lihao1214** [comment]
![Untitled Document](https://user-images.githubusercontent.com/71319702/95642631-fcaed880-0aa9-11eb-9e80-6024a10135dc.jpg)

**Comment by miw-upm** [comment]
No se debe fusionar (merge) origin/develop into issue, solo se debe hacer merge con ramas locales. Primero se debe actualizar develop siempre con avance rápido respecto origin/develop

**Comment by miw-upm** [comment]
Debes repasar el flujo de trabajo, entre las 3:00 y 3:09 del 10/10/2020 no se sigue las indicaciones de como se trabaja con el flujo
