### ISSUE TITLE
POST ReservationSporty

### ISSUE THREAD

**Issue by mbendohhoulaouini** [miw-upm/apaw-practice#232]
This request creates a reservation for a sports activity.

**Comment by miw-upm** [comment]
Hola, solo se puede poner una etiqueta de estimación (poinsts)

**Comment by mbendohhoulaouini** [comment]
Buenas tardes, al final cambie la estimación inicial de (3 horas) ya que era bastante complejo el desarrollo, y le he puesto 5 horas a la historia.

Un cordial saludo.
