### ISSUE TITLE
Airport Model

### ISSUE THREAD

**Issue by ybrooks08** [miw-upm/apaw-practice#260]
![airport_models](https://user-images.githubusercontent.com/68606622/149637283-3ca140e0-331c-4c28-af7e-d56a123e01f3.png)

**Comment by miw-upm** [comment]
Este merge es incorrecto: 975033d2 ybrooks08 <68606622+ybrooks08@users.noreply.github.com> on 14/01/2022 at 23:36, antes de incorporar a develop, cuando este ha evolucionado, debe fusionarse develop dentro de nuestra rama

**Comment by ybrooks08** [comment]
Intenté fusionar develop dentro de mi rama antes de incorporar a develop como me orientó en este último commit e99b81ff55d0d07ebbce3beed360c70927e5ff7e, pero no me detectó cambios a fusionar, entonces procedí a incorporarla.

**Comment by miw-upm** [comment]
Este merge es incorrecto: 975033d2 ybrooks08 <68606622+ybrooks08@users.noreply.github.com> on 14/01/2022 at 23:36.
antes de incorporar a develop, cuando este ha evolucionado, debe fusionarse develop dentro de nuestra rama
