### ISSUE TITLE
Football Persistence

### ISSUE THREAD

**Issue by Sergiomerayo** [miw-upm/apaw-practice#28]
- [x] Crear el modelo de entidades.
- [x] Crear los DAOs (Repositorios).
- [x] Crear una clase para poblar las BD: Seeder<Story>Service e integrarlo con DatabaseSeederService.
- [x] Tests

**Comment by miw-upm** [comment]
Cuando develop ha evolucionado, se debe incorporar develop a nuestro issue: 256a5a3e sergiomerayo <sergiomerayo@gmail.com> on 04/10/2021 at 19:55
