### ISSUE TITLE
Library Model

### ISSUE THREAD

**Issue by netoap** [miw-upm/apaw-practice#30]
Create classes like Book, Category, Reader, Author to model the relationship (1:n, n:1 & n:n ) between classes.

![library models_](https://user-images.githubusercontent.com/33005241/137986996-bd61ddfe-531c-4ffc-aaed-e9239278b3d2.png)

**Comment by miw-upm** [comment]
Falta añadir la referencia del issue en el mensaje del commit: Added library.models.png and 4 class dto 412392bb netoap <alexanderneto5@gmail.com> on 09/10/2021 at 18:53.  Los tiempos consumidos deben ser fieles a la realidad
