### ISSUE TITLE
Bus Ticket Model

### ISSUE THREAD

**Issue by wzwzDev** [miw-upm/apaw-practice#301]

**Comment by wzwzDev** [comment]
- [x] Add Bus Ticket UML
- [x] Create Bus Ticket Models

**Comment by miw-upm** [comment]
Hola, si en el mensaje del commit no aparece en numero del issue no deja rastro, debe ser " #301". Commit erroneo: 6ff2d508 newfb <waelwzwz@gmail.com> on 17/10/2022 at 21:58

**Comment by miw-upm** [comment]
Hola, antes de fusionar con a develop, debes fusionar develop en nuestra rama, cuando develop ha evolucionado respecto de donde comenzó la rama. Commit del error: 0e94b5cf newfb <waelwzwz@gmail.com> on 19/10/2022 at 6:13

**Comment by wzwzDev** [comment]
> Hola, antes de fusionar con a develop, debes fusionar develop en nuestra rama, cuando develop ha evolucionado respecto de donde comenzó la rama. Commit del error: [0e94b5c](https://github.com/miw-upm/apaw-practice/commit/0e94b5cfc13d5ca2177fdfad4dc9284038f2384c) newfb [waelwzwz@gmail.com](mailto:waelwzwz@gmail.com) on 19/10/2022 at 6:13

Ya lo he solucionado

**Comment by miw-upm** [comment]
Este commit es innecesario: e07eeda6 Wael Louati <waelwzwz@gmail.com> on 11/01/2023 at 11:49

**Comment by miw-upm** [comment]
Este commit es innecesario, develop ya estaba actualizado: ce60de74 Wael Louati <waelwzwz@gmail.com> on 12/01/2023 at 18:45

**Comment by miw-upm** [comment]
Este commit es innecesario, develop ya estaba actualizado: f415b07e Luis Lemus <luis.lemus@alumnos.upm.es> on 12/01/2023 at 19:54
