### ISSUE TITLE
Cinema model

### ISSUE THREAD

**Issue by daviwix** [miw-upm/apaw-practice#302]
![cinema models](https://user-images.githubusercontent.com/5365410/194150964-03827120-1e97-4e5a-82d8-63d58fca83e4.png)

**Comment by miw-upm** [comment]
Hola, veo que ya lo has reconducido. El warning son avisos que no quita nota. El error fue que no se deben fusionar ramas remotas con locales, solo se permite avance rápido de ramas locales respecto a las remotas. Commit: 2e7a46e4 david <david.lopez.gracia@alumnos.upm.es> on 01/10/2022 at 13:56
