### ISSUE TITLE
Hiking model

### ISSUE THREAD

**Issue by taras-podolchak** [miw-upm/apaw-practice#303]
![hiking models](https://user-images.githubusercontent.com/5365410/194152706-e508f904-2e92-41d8-a08f-8c297498830c.png)

**Comment by miw-upm** [comment]
Hola, en todos los comentarios debe aparecer el issue de forma aislada " #303 " con blanco por delante y detrás

**Comment by taras-podolchak** [comment]
Reabierto para corregir la clase Event
