### ISSUE TITLE
Restaurant Model

### ISSUE THREAD

**Issue by shenHui-Cheng** [miw-upm/apaw-practice#309]
![restaurant models](https://user-images.githubusercontent.com/5365410/196805060-af57c8f4-a0eb-478b-8228-e430a506bf48.png)

**Comment by miw-upm** [comment]
Hola, el flujo es incorrecto, no puede haber commits en fusiones entre develop local y remoto. Repasa la práctica de devops para ver como es el flujo de trabajo.
