### ISSUE TITLE
Pharmacy Model

### ISSUE THREAD

**Issue by 1257198442** [miw-upm/apaw-practice#313]
![pharmacy models](https://user-images.githubusercontent.com/5365410/193678179-594e5c58-df90-42a3-a5f2-51714c1c3756.png)

**Comment by miw-upm** [comment]
Hola, antes de incorporar el issue a develop, se debe incorporar develop a la rama issue, si develop ha evolucionado respecto al punto donde empezamos el issue. Repasa el flujo de trabajo visto en devops
