### ISSUE TITLE
Designing Persistence for restaurant

### ISSUE THREAD

**Issue by shenHui-Cheng** [miw-upm/apaw-practice#318]

**Comment by miw-upm** [comment]
Hola, tal como pones los mensajes en los commits de merge, no dejan rastro en el issue de github: f7ab9359 shenhui cheng <shenhui.cheng@alumnos.upm.es> on 16/10/2022 at 14:39

**Comment by shenHui-Cheng** [comment]
Si, perdón, es que al principio lo hice con comando y con mensaje en el comando pero luego me dijo un compañero que no hace falta. Pero ya entiendo, lo haré luego todos con comandos.
