### ISSUE TITLE
GET/ 	films/search?q=screenNumber:screenNumber 

### ISSUE THREAD

**Issue by Mariavernia** [miw-upm/apaw-practice#33]

**Comment by Mariavernia** [comment]
request: screenNumber
response: {[films]}

**Comment by miw-upm** [comment]
Cuando se incorpora issue a develop, siempre hay que poner --no-ff, aqui se te ha olvidado: merge develop into issue #33 c2935046 Mariavernia <maversa2@alumni.uv.es> on 16/10/2021 at 21:06
