### ISSUE TITLE
GET Author

### ISSUE THREAD

**Issue by LiuxuranUPM** [miw-upm/apaw-practice#331]

**Comment by miw-upm** [comment]
El commit f61e86d8 (19/10/2020 21:13) es redundante, ya que nadie había evolucionado develop desde tu aportación parcial

**Comment by LiuxuranUPM** [comment]
> El commit [f61e86d](https://github.com/miw-upm/apaw-practice/commit/f61e86d89f5dc74c6518c4117427375775f185ab) (19/10/2020 21:13) es redundante, ya que nadie había evolucionado develop desde tu aportación parcial

Gracias maestro por tu recordatorio. Debido a que casi había completado las cinco funciones cuando cargué el # 331 antes, lo dividí y lo cargué nuevamente。
