### ISSUE TITLE
POST Type

### ISSUE THREAD

**Issue by LiuxuranUPM** [miw-upm/apaw-practice#332]

**Comment by miw-upm** [comment]
La gestión del proyecto debe estar alineado con la realidad de su desarrollo, no es adecuado simular una gestión a posteriori de implementar el código

**Comment by LiuxuranUPM** [comment]
> La gestión del proyecto debe estar alineado con la realidad de su desarrollo, no es adecuado simular una gestión a posteriori de implementar el código. Si analizas la secuencia, a las 11:48 mueves el issue a la columna de progreso, 13:56 le cambias la estimación, a las 22:28 cierras el issue, a las 22:28 pones el tiempo tardado, no hay rastro de los commits de su código y después aparecen referencia de commits un día después.

Gracias maestra por tu recordatorio, he reorganizado
