### ISSUE TITLE
Designing Persistence for Pharmacy

### ISSUE THREAD

**Issue by 1257198442** [miw-upm/apaw-practice#335]

**Comment by miw-upm** [comment]
Hola, por una parte se ha dejado roto develop y no se ha atendido. Además los tiempos de los commits no se corresponden a un desarrollo lógico del código.

**Comment by miw-upm** [comment]
Hola, ha vuelto a romper la rama desarrollo y la dejas abandonada. Si lo vuelves a repetir, me veré obligado a desactivar tu cuenta. Un saludo
