### ISSUE TITLE
Create method DELETE for pharmacy

### ISSUE THREAD

**Issue by 1257198442** [miw-upm/apaw-practice#365]

**Comment by miw-upm** [comment]
Hola, tal como pones los mensajes en estos commits, no quedan reflejados en el issue: 5253a33c 1257198442 <1257198442@qq.com> on 16/10/2022 at 13:41

**Comment by 1257198442** [comment]
Hola, no sé por qué se refleja que he hecho cambios sobre el modelo family 5253a33, esto se supone es de otro compañero,  lo que hice fue cambiar rama en develop, después un fetch y merge con origin develop para ver si hay cambios y bajarlo. Luego en mi issue#365, un merge de develop y cambio a develop para hacer un merge de mi issue#365, y al final subir mi develop local a remoto.
No entiendo el error de workflow.

**Comment by miw-upm** [comment]
Hola, porque en el mensaje del merge no hay un blanco entre la palabra issue y el número, debiera ser:
"Merge branch issue #365 into develop", así que estas fusiones hay que hacerlas por comando git para que se pueda controlar el mensaje que se pone
