### ISSUE TITLE
Patrón 2 Composite

### ISSUE THREAD

**Issue by jcmquintero** [miw-upm/apaw-practice#397]
Composite sobre Monitor, solo en el modelo del dominio.

**Comment by miw-upm** [comment]
Hola, estos commit son innecesarios: 76cd778c Juan Carlos <marquez28@correo.ugr.es> on 20/10/2022 at 20:06, a25e33b9 Juan Carlos <marquez28@correo.ugr.es> on 20/10/2022 at 20:28, b0ae6ea3 Juan Carlos <marquez28@correo.ugr.es> on 20/10/2022 at 21:19
