### ISSUE TITLE
Create PATCH University end-point

### ISSUE THREAD

**Issue by VictrCV** [miw-upm/apaw-practice#42]
PATCH /subjects
request: [{reference, credits}]

**Comment by VictrCV** [comment]
I reopen this issue in order to fix this end-point (as it's a put end-point, instead of a patch one) and to add its service tests

**Comment by miw-upm** [comment]
Este commit es innecesario: merge develop into #42 7c0ffb09 Víctor Claramunt <victor.claramuntv@alumnos.upm.es> on 15/10/2021 at 0:40
