### ISSUE TITLE
College model

### ISSUE THREAD

**Issue by luisEnriqueLemus** [miw-upm/apaw-practice#427]

**Comment by luisEnriqueLemus** [comment]
![Image](https://user-images.githubusercontent.com/113717468/211209188-ca7d398f-6917-4ac8-b251-99967b7864df.png)

**Comment by luisEnriqueLemus** [comment]
The assigmentSubject model have the attribute grade because the student is promoted even if he fails a subject, which he must take in the next grade.

**Comment by miw-upm** [comment]
Este commit es innecesario, el issue ya estaba actualizado: 82bb7ca0 Luis Lemus <luis.lemus@alumnos.upm.es> on 04/01/2023 at 12:43
