### ISSUE TITLE
Climbing Model

### ISSUE THREAD

**Issue by davidyareth** [miw-upm/apaw-practice#452]
![climbing models](https://github.com/miw-upm/apaw-practice/assets/5365410/658c29c8-6d43-4335-a454-e215b0785015)

**Comment by miw-upm** [comment]
El error esta en este commit: fab2ced3 David Yareth Macaya Albericio <davidyareth@gmail.com> on 04/10/2023 at 0:01
Antes de incorporar los cambios a develop, se deben poner los cambios en nuestra issue si develop ha evolucionado.
