### ISSUE TITLE
Formula One model

### ISSUE THREAD

**Issue by oliver-upm** [miw-upm/apaw-practice#456]
![image](https://github.com/miw-upm/apaw-practice/assets/143716576/53204e69-089e-46da-ab91-04cd5b74c9dc)

**Comment by miw-upm** [comment]
Buenas tardes, este commit: 7bd144dd Oliver Fernandez <oliver.fernandez@alumnos.upm.es> on 02/10/2023 at 18:01
El mensaje debiera ser Merge branch #456 into develop, sino, no aparece rastro en este issue de ese merge
