### ISSUE TITLE
Restaurant Model

### ISSUE THREAD

**Issue by adriancastrovilar** [miw-upm/apaw-practice#457]
[Link al Diagrama de Clases siempre actualizado](https://app.diagrams.net/#G1G7XsRIwm77kveVV_GqWpU3waJM-pU_tD)

![models restaurant](https://github.com/miw-upm/apaw-practice/assets/144701686/13478f62-1b35-4c25-9d49-7c7fe96ed903)

**Comment by miw-upm** [comment]
Buenas tardes, este commit: d955189d adriancastrovilar <adrian.castrov@alumnos.upm.es> on 02/10/2023 at 17:30
Está mal realizado!! antes de incorporar debes hacer un fetch, ya habían pasado 13 minutos. Se debe hacer el fetch justo antes de subir
