### ISSUE TITLE
Museum model

### ISSUE THREAD

**Issue by diego-guerrero** [miw-upm/apaw-practice#458]
![Museum model](https://github.com/miw-upm/apaw-practice/blob/develop/docs/museum.models.png?raw=true)

**Comment by miw-upm** [comment]
El commit, f7a522aa Diego Guerrero <diego.guerreroc@alumnos.upm.es> on 01/10/2023 at 19:34, En los mensajes, se debe referenciar  " #*" de forma aislada, en el merge no se hace bien.

**Comment by miw-upm** [comment]
Por eso, no se refleja en este issue el merge

**Comment by diego-guerrero** [comment]
Reopened to review model diagram and entities

**Comment by diego-guerrero** [comment]
Reopened to review model diagram and entities

**Comment by diego-guerrero** [comment]
Reopened to review model diagram and entities
