### ISSUE TITLE
Horse Stable Model

### ISSUE THREAD

**Issue by NataliaLM** [miw-upm/apaw-practice#461]
![stable models](https://github.com/miw-upm/apaw-practice/assets/5365410/61cdcfb7-aa9b-43e6-a53b-61617ba41780)

**Comment by miw-upm** [comment]
El error está en este commit: cea96780 NataliaLM <natalia.arq.123@gmail.com> on 04/10/2023 at 1:09
El mensaje del merge debe incluir " #461", sino, no deja rastro en el issue
Antes de incorporar los cambios a develop, se deben poner los cambios en nuestra issue si develop ha evolucionado.

**Comment by miw-upm** [comment]
Este commit es erroneo: cea4601a NataliaLM <natalia.arq.123@gmail.com> on 04/10/2023 at 22:11
Vuelves a cometer el mismo error.
Este commit es redundante: dba312f6 NataliaLM <natalia.arq.123@gmail.com> on 04/10/2023 at 22:36
Y este commit, tenía que haber seguido el issue, y no partir de develop:734191f8 NataliaLM <natalia.arq.123@gmail.com> on 04/10/2023 at 23:17.

Observo que no tienes bien cogido el flujo, te recomiendo que repases la practica de devops...

**Comment by miw-upm** [comment]
Hola, este commit es erroneo: 3b9e68a5 NataliaLM <natalia.arq.123@gmail.com> on 08/10/2023 at 12:06
