### ISSUE TITLE
1️⃣ Subway Model

### ISSUE THREAD

**Issue by rodriCalleA** [miw-upm/apaw-practice#463]
![subway models](https://github.com/miw-upm/apaw-practice/assets/5365410/50d2ccc1-0e47-4d04-a768-c1482f78fd7a)

**Comment by rodriCalleA** [comment]
![Image](https://github.com/miw-upm/apaw-practice/assets/123869905/70bb4fe5-3828-49ab-be9e-f27237ea1149)

**Comment by miw-upm** [comment]
Este commit es erroneo: 604aa828 Rodrigo de la Calle <rodricalle@usal.es> on 05/10/2023 at 11:43
Se debía primero incorporar el avance de develop a nuestro issue
