### ISSUE TITLE
Hospital Model

### ISSUE THREAD

**Issue by 99nnss** [miw-upm/apaw-practice#470]
![hospital model](https://github.com/miw-upm/apaw-practice/assets/101188999/7d1060d1-de10-4aab-9f50-e976b969313b)

**Comment by miw-upm** [comment]
Este commit: 635b1d88 LeLiu <le.liu@alumnos.upm.es> on 05/10/2023 at 23:21
Y este es erroneo: 45d1ff4c LeLiu <le.liu@alumnos.upm.es> on 05/10/2023 at 23:24
recuerdo que si el flujo no se hace adecuadamente, no se podrá aprobar la asignatura
