### ISSUE TITLE
Coffee Shop Model

### ISSUE THREAD

**Issue by AimerSQL** [miw-upm/apaw-practice#473]
![image](https://github.com/miw-upm/apaw-practice/assets/35105605/4e7b9567-bdcf-45a2-b213-5a09a69ccc4a)

**Comment by miw-upm** [comment]
Este commit no sigue el flujo establecido en la asignatura: 98cec0e5 dSHEN <dshen123456@gmail.com> on 03/10/2023 at 21:16

**Comment by miw-upm** [comment]
Estos commits: d55189f1 dSHEN <dshen123456@gmail.com> on 05/10/2023 at 19:56 
Y este: 9809b37a dSHEN <dshen123456@gmail.com> on 05/10/2023 at 19:58

Denotan una falta de conocimiento de como se aporta código a develop. Ruego practique antes con la práctica de devops, antes de cometer este tipo de errores
