### ISSUE TITLE
Influencer Agency Model

### ISSUE THREAD

**Issue by hugovdocampo** [miw-upm/apaw-practice#475]
![influencer_agency models](https://github.com/miw-upm/apaw-practice/assets/5365410/9ba5a243-c126-4914-8e6c-4f6b5231f5db)

**Comment by hugovdocampo** [comment]
![Image](https://github.com/miw-upm/apaw-practice/assets/145801605/a51712fe-2ad5-4077-a130-7e32f8fc145f)

**Comment by miw-upm** [comment]
Hola, lo atributos deben ser privados y además, un atributo que representa una lista no puede estar en singular, sino que debe ser plural ( campigns y otros). Cambio esto, cierra el issue y puedes continuar
