### ISSUE TITLE
Padel Academy Model

### ISSUE THREAD

**Issue by ghost** [miw-upm/apaw-practice#476]
![padel_academy models](https://github.com/miw-upm/apaw-practice/assets/5365410/10a0d972-58b8-4f15-bcfa-1859b96650f6)

**Comment by michaelhr97** [comment]
![padel_academy models](https://github.com/miw-upm/apaw-practice/assets/143937334/e70e890b-8f38-42e7-b2ce-f6e8cd30c5b7)

**Comment by miw-upm** [comment]
Buenas tardes, este mensaje de commit es incorrecto: Merge branch 'issue#476' into develop, debiera ser Merge branch #476 into develop, fue realizado en este commit: 94ea0e96 Michael Hernandez <michaelhernandezrala@gmail.com> on 02/10/2023 at 15:18

**Comment by miw-upm** [comment]
Este commit es incorrecto: 94ea0e96 Michael Hernandez <michaelhernandezrala@gmail.com> on 02/10/2023 at 15:18, antes de incorporar a develop, debieras haber incorporado develop en tu rama.

**Comment by michaelhr97** [comment]
![padel_academy models](https://github.com/miw-upm/apaw-practice/assets/143937334/25f7874a-55fd-4e13-82dd-0345079a5c4f)

**Comment by michaelhr97** [comment]
![padel_academy models](https://github.com/miw-upm/apaw-practice/assets/143937334/68d0cc72-14ce-4b7d-bcc4-d161b17b4e45)

**Comment by michaelhr97** [comment]
![padel_academy models](https://github.com/miw-upm/apaw-practice/assets/143937334/767a943d-f270-4161-a751-0a20984bc1db)

**Comment by michaelhr97** [comment]
![padel_academy models](https://github.com/miw-upm/apaw-practice/assets/143937334/ef06d5c1-60ba-4cbe-9328-1327cbdfe5d5)

**Comment by miw-upm** [comment]
Hola, este commit es erroneo: 8f676231 Michael Hernandez <michaelhernandezrala@gmail.com> on 03/10/2023 at 1:11
Este mismo error ya te lo avisé y lo has vuelto a cometer: antes de incorporar a develop, debieras haber incorporado develop en tu rama.

**Comment by ghost** [comment]
![padel_academy models](https://github.com/miw-upm/apaw-practice/assets/143937334/75dc5685-0d51-4370-be7f-7a4346ff7532)
