### ISSUE TITLE
Videogame Company Model

### ISSUE THREAD

**Issue by rvemon** [miw-upm/apaw-practice#477]
![videogame_company models](https://github.com/miw-upm/apaw-practice/assets/5365410/c19cf799-23cd-44a4-9df9-ed9c0a9134f7)

**Comment by miw-upm** [comment]
Buenas tardes: este commit: 074d4cb0 ricardo.vente <ricardo751991@gmail.com> on 02/10/2023 at 19:01
Es peligroso, si origin/develop no esta en avance rápido con develop, debes borrar tu develop local y ponerlo fisicamente en el commit de origin/develop

**Comment by miw-upm** [comment]
Hola, este commit: eea75c37 ricardo.vente <ricardo751991@gmail.com> on 02/10/2023 at 22:17
tiene otro error, antes de incorporar los cambios a develop, hay que meter los cambios en nuestra rama, cuando este a evolucionado
