### ISSUE TITLE
Football Competition Model

### ISSUE THREAD

**Issue by ruliworst** [miw-upm/apaw-practice#481]
![football_competition models](https://github.com/miw-upm/apaw-practice/assets/5365410/32d8a248-cccb-4540-ab00-e6b120deda37)

**Comment by ruliworst** [comment]
![football_competition models](https://github.com/miw-upm/apaw-practice/assets/66559228/b2d0e301-94d1-421b-8a06-fee3a914eaf4)

**Comment by miw-upm** [comment]
Este commit es erroneo: 0b16bdfe ruliworst <raulfa1503@gmail.com> on 02/10/2023 at 23:12
Antes de fusionarse con develop, debe fusionarse develop con el issue, cuando este ha evolucionado

**Comment by ruliworst** [comment]
Issue cerrada tras hacer los cambios necesarios.

**Comment by ruliworst** [comment]
![football_competition models](https://github.com/miw-upm/apaw-practice/assets/66559228/611024b1-972f-42c6-ba5f-9135ebda02d8)

**Comment by ruliworst** [comment]
Se cierra la issue.
