### ISSUE TITLE
Car Workship persistence desing

### ISSUE THREAD

**Issue by bdmariobd** [miw-upm/apaw-practice#488]
Que hacer?

- Crear el modelo de entidades.
- Crear los DAOs (Repositorios).
- Crear una clase para poblar las BD: <Story>SeederService e integrarlo con DatabaseSeederService

**Comment by miw-upm** [comment]
El error esta en este commit: 54565d4d Mario <mario10_bd@hotmail.com> on 04/10/2023 at 9:13
El mensaje del merge debe incluir " #488", sino, no deja rastro en el issue
Antes de incorporar los cambios a develop, se deben poner los cambios en nuestra issue si develop ha evolucionado.
