### ISSUE TITLE
Car Workshop PUT endpoint

### ISSUE THREAD

**Issue by bdmariobd** [miw-upm/apaw-practice#523]
PUT cars-to-repair/{registration-number}/model

**Comment by miw-upm** [comment]
El error está en este commit: 87de6d4f Mario Blanco <mario10_bd@hotmail.com> on 10/10/2023 at 14:43

**Comment by miw-upm** [comment]
Este commit es redundante: edad57f7 Martahc <martahica@gmail.com> on 10/10/2023 at 16:08
