### ISSUE TITLE
Create PUT Hospital endpoint

### ISSUE THREAD

**Issue by AdrianCV412** [miw-upm/apaw-practice#56]
Corresponding to -> PUT/patients/{dni}

Updates all the values in a patient.

**Comment by miw-upm** [comment]
Este commit es innecesario: Merge develop into #56 fd950e10 Adrian <adrian.callejo@alumnos.upm.es> on 18/10/2021 at 13:13

**Comment by miw-upm** [comment]
Y este tambie´n: Merge develop into #56 99e45b9c Adrian <adrian.callejo@alumnos.upm.es> on 18/10/2021 at 13:29
