### ISSUE TITLE
Bank Persistance

### ISSUE THREAD

**Issue by jorgempavon** [miw-upm/apaw-practice#588]

**Comment by miw-upm** [comment]
Hola, cuando veas que te rechaza el subir develop, se hace un fetch y compruebas que te han adelantado en la subida. Entonces la mejor solución es borrar tu develop local y situarlo en el origin/develop, incorporar develop a tu issue y volver a intentar fusionar con develop y subir. El commit del error es: 64ce4491 Jorge <jorge.mpavon@alumnos.upm.es> on 15/10/2023 at 16:46

**Comment by jorgempavon** [comment]
Buenos días,

Diculpa el error, ayer desde mi develop local me actualicé con la remota 
e incorporé
mis cambios a mi rama issue#588. Una vez hecho esto fusioné la issue 
hacia develop,
pero se produjo una actualización en el remoto, hice un fetch mergee los 
cambios con remoto
y subí.
Muchas gracias por el aviso,
Un saludo.
