### ISSUE TITLE
FurnitureStore GET Endpoint

### ISSUE THREAD

**Issue by abvsba** [miw-upm/apaw-practice#596]

**Comment by miw-upm** [comment]
Hola, a estas alturas este tipo de errores ya esta fuera de lugar: 77069706 jiaan <chengjiaan123@gmail.com> on 13/10/2023 at 17:42

**Comment by miw-upm** [comment]
Utilizas un develop obsoleto, recuerda que siempre se debe hacer fetch, y actualizar develop local, donde este el origin/develop
