### ISSUE TITLE
VideoGame entities model

### ISSUE THREAD

**Issue by nataliacasanova** [miw-upm/apaw-practice#61]

**Comment by nataliacasanova** [comment]
![modelo_entidades](https://user-images.githubusercontent.com/71524430/95139477-d0731f00-076c-11eb-977c-9f31fbddeb2f.png)

**Comment by nataliacasanova** [comment]
![modelo_entidades](https://user-images.githubusercontent.com/71524430/95139530-f993af80-076c-11eb-8e8d-59f3920b98f7.png)

**Comment by miw-upm** [comment]
Hola Natalia, Las fusiones (merge) siempre se realizan con ramas locales, cuando origin/develop a avanzado respecto a l nuestra local develop, lo primero es activar develop y la fusionamos con origin/develop CON avance rápido (es decir, NO se pone --no-ff) y una vez que develop ya está actualizada, fusionamos develop dentro de nuestro issue
