### ISSUE TITLE
Hospital model Persistence

### ISSUE THREAD

**Issue by 99nnss** [miw-upm/apaw-practice#639]
Crear el modelo de entidades.
Crear los DAOs (Repositorios).
Crear una clase para poblar las BD: SeederService e integrarlo con DatabaseSeederService.

**Comment by 99nnss** [comment]
Crear el modelo de entidades.
Crear los DAOs (Repositorios).
Crear una clase para poblar las BD: HospitalSeederService e integrarlo con DatabaseSeederService.

**Comment by miw-upm** [comment]
Este es el commit erroneo: f7ca7d09 LeLiu <le.liu@alumnos.upm.es> on 12/10/2023 at 23:33
