### ISSUE TITLE
Car Dealership entities model

### ISSUE THREAD

**Issue by PabloCC** [miw-upm/apaw-practice#68]
- Crear 4 documentos. No puede haber 2 documentos con el mismo nombre en toda la aplicación.

Cada documento: >=2 atributos + [id:String].
Total >= 16 atributos, con al menos LocalDateTime, Boolean y uno numérico (Integer, Double, Long o BigDecimal).
Los atributos para manejo de dinero deben ser BigDecimal.
Relaciones necesarias: 1..n, n..1 y n..n.

- Crear los DAOs (Repositorios).
- Crear una clase para poblar las BD: Seeder<Story>Service e integrarlo con DatabaseSeederService.

**Comment by PabloCC** [comment]
![image](https://user-images.githubusercontent.com/12677669/95620213-1cc1a600-0a70-11eb-9860-08fe7b12cb42.png)

**Comment by miw-upm** [comment]
No se debe fusionar (merge) origin/develop into issue, solo se debe hacer merge con ramas locales. Primero se debe actualizar develop siempre con avance rápido respecto origin/develop

**Comment by PabloCC** [comment]
Actualizo el diagrama de clases.
![carDealership](https://user-images.githubusercontent.com/12677669/95650067-672f3b00-0ae1-11eb-8f38-0f41252593c5.png)
