### ISSUE TITLE
Library Second Search

### ISSUE THREAD

**Issue by jyf0209** [miw-upm/apaw-practice#786]
dado name de Library, obtener la media de los numberOfBook asociados

**Comment by miw-upm** [comment]
Este commit es redundante: 10f012ef jinyifan <563503448@qq.com> on 20/10/2023 at 7:25

**Comment by miw-upm** [comment]
Este commit es redundante: 88622d07 jinyifan <563503448@qq.com> on 20/10/2023 at 7:42

**Comment by miw-upm** [comment]
Este commit es redundante: fcde4cc1 jinyifan <563503448@qq.com> on 20/10/2023 at 8:01
