### ISSUE TITLE
Persistence game-wow

### ISSUE THREAD

**Issue by Eywen** [miw-upm/apaw-practice#80]
![game_wow_model drawio](https://user-images.githubusercontent.com/23658647/136655722-40409187-b1ba-4234-864b-482b6752aab7.png)

Modificado  modelo agregando el campo titulo en la clase Drop
Create entity model.
Create DAOs (Repositorios).
Create DB populating classes and integrate with DatabaseSeederService.

**Comment by miw-upm** [comment]
Aquí has fusionado issue 80 into develop sin poner --no-ff, habiendo hecho avance rápido: e765dfe7 Blanca <b.castano@almatech.es> on 08/10/2021 at 14:50
