### ISSUE TITLE
Hospital Model

### ISSUE THREAD

**Issue by IvanEsteban94** [miw-upm/apaw-practice#825]

**Comment by miw-upm** [comment]
Cuando realices commits, debes incluir en el mensaje: #825 con el número del issue, siendo en este caso 825: 
cceace7f Ivan Esteban, aa16f5aa Ivan Esteban, 6c96d8f2 estedosunidos

**Comment by miw-upm** [comment]
Antes de incorporar el issue a develop, debéis hacer un fetch y actualizar develop local al punto donde este origin/develop. Este commit es erroneo: 6db9d891 estedosunidos

**Comment by miw-upm** [comment]
Cuando develop a evolucionado respecto al issue, lo primero es merge de develop dentro del issue, y por último, merge del issue a develop: db9fc107 estedosunidos
