### ISSUE TITLE
Company Model

### ISSUE THREAD

**Issue by h-zhu25** [miw-upm/apaw-practice#831]

**Comment by h-zhu25** [comment]
![Company](https://github.com/user-attachments/assets/e18353eb-3582-4c31-ae5e-222c6529b028)

**Comment by miw-upm** [comment]
Este commit es erroneo: 46e79a25 zhuha

**Comment by miw-upm** [comment]
![Company](https://github.com/user-attachments/assets/cf79a2e7-6bd9-4bbc-89da-d671faf6022f)
