### ISSUE TITLE
Movies model

### ISSUE THREAD

**Issue by victormartindz** [miw-upm/apaw-practice#835]
- [x] Create Class Studio
- [x] Create Class Movie
- [x] Create Class Actor
- [x] Create Class Award

**Comment by victormartindz** [comment]
![movies](https://github.com/user-attachments/assets/e3066d30-0987-409e-82f3-1c8040b16db0)

**Comment by victormartindz** [comment]
![movies](https://github.com/user-attachments/assets/9c225575-0af7-4180-a083-c059df52ceb1)

**Comment by miw-upm** [comment]
Este commit no era necesario, ya estabas actualizado con develop: c8efc35d victormartindz <victor.martin.dz@gmail.com> on 06/10/2024 at 22:00
