### ISSUE TITLE
Car model

### ISSUE THREAD

**Issue by Javi-100** [miw-upm/apaw-practice#837]

**Comment by Javi-100** [comment]
![Image](https://github.com/user-attachments/assets/850875a9-af93-4f1e-ac6e-77a3bcc33384)

In the code, the Owner class is called OwnerCar to distinguish it and to avoid conflict with other models that also have a class called Owner.

**Comment by miw-upm** [comment]
Antes de incorporar el issue a develop, debéis hacer un fetch y actualizar develop local al punto donde este origin/develop. Este commit es erroneo: 79566c22 JAVIER ARANDA

**Comment by miw-upm** [comment]
Hola, repites el error: 8a7297af JAVIER ARANDA
