### ISSUE TITLE
Hospital Persistence

### ISSUE THREAD

**Issue by IvanEsteban94** [miw-upm/apaw-practice#852]

**Comment by miw-upm** [comment]
Merge remote-tracking branch 'origin/develop' into issue#852 b0b38de6 estedosunidos

**Comment by miw-upm** [comment]
Merge branch 'develop' of https://github.com/miw-upm/apaw-practice into develop
900cc3ba estedosunidos

**Comment by miw-upm** [comment]
Merge branch 'develop' of https://github.com/miw-upm/apaw-practice into develop
d2c6484b estedosunidos <ivaneestebanvargasmartines@gmail.com> on 09/10/2024 at 20:23

**Comment by miw-upm** [comment]
Merge branch 'develop' of https://github.com/miw-upm/apaw-practice into develop
35a72742 estedosunidos <ivaneestebanvargasmartines@gmail.com> on 13/10/2024 at 13:34
