### ISSUE TITLE
Tennis Courts Model

### ISSUE THREAD

**Issue by andresTorrecillas** [miw-upm/apaw-practice#9]
![TennisCourts models](https://user-images.githubusercontent.com/5365410/140056882-30e7be81-a41d-4ff3-a9e2-8141a9773c02.png)

**Comment by miw-upm** [comment]
El commit: c6af0b1c aTorrecillas <a.torrecillas@alumnos.upm.es> on 29/09/2021 at 20:27, es redundante, ya que develop no había evolucionado.
